### PR TITLE
stop button in red color [css]

### PR DESCRIPTION
**Pull request by swapnalshahil**
stop button in red color looks better! :)

### CODE REVIEW

**Comment by avinash201199** [comment]
pull request merged :)
follow for more

**Comment by avinash201199** [comment]
image
No changes being reflected :) please correct it

**Comment by swapnalshahil** [comment]
Hey it will take time!

**Comment by swapnalshahil** [comment]
use ctrl + shift +R to hard refresh after some time!

**Comment by avinash201199** [comment]
Thank you for your contribution :)
follow for more

**Pull request merged**
