### PR TITLE
added changes in pomodoro

### PR DESCRIPTION
**Pull request by And-Rahul**
Added stop watch button in pomodoro nav bar and made play and reset as buttons in pomodoro page.
Screenshot 2021-10-07 at 10 01 44 AM

### CODE REVIEW

**Comment by avinash201199** [comment]
good work :)
follow for more

**Comment by And-Rahul** [comment]
Thank you!

**Comment by avinash201199** [comment]
> Thank you!

hey please look stop watch button is taking back to home page and pomodoro timer is not working

**Comment by And-Rahul** [comment]
Yes, Podomore timer is not a button. I you want it I can add.

**Comment by avinash201199** [comment]
> Yes, Podomore timer is not a button. If you want it I can add.

also solve the stop watch functionality

**Pull request merged**
