### PR TITLE
fullyresponsive

### PR DESCRIPTION
**Pull request by arunsingh009**
it is fully responsive now
watch resp 3
watch resp2
watch resp1
stopwatch resp

### CODE REVIEW

**Comment by arunsingh009** [comment]
it solves issue no 44

**Comment by avinash201199** [comment]
hey ,please solve the branch conflict :)
fork again and then copy paste your changes

**Comment by arunsingh009** [comment]
do i have to paste this screenshots again

**Comment by avinash201199** [comment]
> do i have to paste this screenshots again

as your wish , but don't change extra thing , just solve the branch conflict 
fork again and copy paste your changes

**Comment by arunsingh009** [comment]
actually i did the changes
after forking
but again
this is showing the same thing

**Comment by avinash201199** [comment]
> actually i did the changes after forking but again this is showing the same thing

sorry
because i just merged one pull request and the changes are different that's why

**Comment by arunsingh009** [comment]
what to do now

**Comment by arunsingh009** [comment]
do i have to do it again

**Comment by avinash201199** [comment]
@arunsingh009 
everyone is working on the same file so whenever I accept any pull request file changes with new code and the people woriking with previous code file face branch conflict :(

**Comment by avinash201199** [comment]
> do i have to do it again

yeah ,you have to fork again

**Comment by arunsingh009** [comment]
ok so please accept my pr first next time

**Comment by arunsingh009** [comment]
i am updating it within 5 min

**Comment by avinash201199** [comment]
> ok so please accept my pr first next time

yeah will accept your pr first :)
you are doing great 
thank you for your contribution

**Comment by arunsingh009** [comment]
hey do u think this is looking good i dont have any issue in making it responsive but the previous one was good whwn it comes to record laps
image

**Comment by avinash201199** [comment]
lap function is not working when i merged the previous pr :(
you can also work on it

**Comment by avinash201199** [comment]
image

the current ui is this

**Comment by arunsingh009** [comment]
ok

**Comment by arunsingh009** [comment]
i am on the merge of completing it
dont take any prs

**Comment by avinash201199** [comment]
> i am on the merge of completing it dont take any prs

yeah don't worry

**Comment by arunsingh009** [comment]
image
is it fine

**Comment by avinash201199** [comment]
> image is it fine

yeah

**Comment by arunsingh009** [comment]
updated the code

**Comment by arunsingh009** [comment]
image
no option of resolve conflicts

**Pull request closed without merging**
