### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by Mohamed-Ayaan358**
Altered the index.html and script.js slightly to adjust to the dark mode changer.

First mode:
image

Second mode:
image

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
@avinash201199 can you please update this before updating the rest this is a significant change in the code than the other PR's

**Comment by Mohamed-Ayaan358** [comment]
So @avinash201199 the "conflicts" are literally me inserting the new elements

**Comment by avinash201199** [comment]
Please solve the conflicts, fork again and then do changes, screen shot show light mode instead of dark mode, closing the pr  . 
Please create an issue first :)

**Comment by Mohamed-Ayaan358** [comment]
I did make a pr and issue

**Pull request closed without merging**
