### PR TITLE
added dark mode in pomodoroTimer, removed scrollbar from pomodoroTime…

### PR DESCRIPTION
**Pull request by helloArnab**
…r, added favicon in pomodoroTimer

### CODE REVIEW

**Comment by helloArnab** [comment]
I have made changes in pomodoro timer 
1. Added Dark Mode ( it will seemlessly change in timer pause and play)
2. Removed the scrollbar from pomodoro
3. At first the favicon is visible only at stopwatch but now it will also be shown in pomodoro

**Comment by helloArnab** [comment]
Screenshot (102)
Screenshot (103)
Screenshot (104)
Screenshot (105)

**Comment by helloArnab** [comment]
Your Timer have dark mode and so it will be trendy to have a dark mood on pomodoro timer too. I hope you like my work and accept my pr. :)

**Comment by avinash201199** [comment]
Thank you for your contribution :)

**Pull request merged**
