### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ujjwalgupta9125**

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
@ujjwalgupta9125  is it cool if you can tell avinash if he can update mine then he can update yours I have put some significant changes to the code.

**Comment by ujjwalgupta9125** [comment]
> @ujjwalgupta9125 is it cool if you can tell avinash if he can update mine then he can update yours I have put some significant changes to the code.

How can I tell to avinash?

**Comment by Mohamed-Ayaan358** [comment]
> > @ujjwalgupta9125 is it cool if you can tell avinash if he can update mine then he can update yours I have put some significant changes to the code.
> 
> How can I tell to avinash? 

All you need to do is press @ then enter avinash and GitHub will tell you his GitHub name this means you are pinging him and tell him to update mine first srry for the discomfort in advance bro

**Comment by ujjwalgupta9125** [comment]
I think he will do whenever he gets time. Isn't it?

**Comment by avinash201199** [comment]
Sorry to say, one word changes are not accepted, officials of hacktoberfest will review every repo and pr so contribute genuine

**Pull request closed without merging**
