### PR TITLE
Merge README improvement issue #60 PR

### PR DESCRIPTION
**Pull request by komalsoni4**
Arranged README in well manner so that reader would not face any difficulty  and you can also close this issue after that because I don't think anything else can be written there, whatever written is enough.

### CODE REVIEW

**Comment by avinash201199** [comment]
resolve conflicts

**Comment by avinash201199** [comment]
fork again to do your changes

**Comment by komalsoni4** [comment]
I resolved conflict

**Comment by avinash201199** [comment]
Hey Komal , tha current readme is already updated , contents have been changed , please delete the repo and then fork to do your changes

**Pull request closed without merging**
