### PR TITLE
functionalitymodification

### PR DESCRIPTION
**Pull request by parzival272000**
Issue:
#9
After change:
Screenshot from 2021-10-03 10-42-40

### CODE REVIEW

**Comment by avinash201199** [comment]
@parzival272000  I like the stop button :)
please don't remove any of the button work on some another feature

**Comment by parzival272000** [comment]
Ok I just changed it to toggle functionalities are same

**Comment by parzival272000** [comment]
Can you atleast give me hacktoberfest-accepted on my this PR or the other one if my efforts were good.

**Comment by parzival272000** [comment]
I made another PR this time i didn't change any buttons etc just added the functionality can you revie it plz

**Pull request closed without merging**
