### PR TITLE
updatedlinkonclickingstopwatchinnavbar

### PR DESCRIPTION
**Pull request by parzival272000**
Just added link to the stopwatch icon in navbar so it takes to this github if someone wants to contribute.

### CODE REVIEW

**Comment by parzival272000** [comment]
It's just a minor enhancement i think it should be fine to merge

**Comment by avinash201199** [comment]
yeah, but after hacktoberfest it will be not required :)
no one will surf it on the internet so not required 
work one something else

**Comment by parzival272000** [comment]
Yeah :) I am working on something else too.
But still

**Comment by avinash201199** [comment]
still don't require :)

**Pull request closed without merging**
