### PR TITLE
footer

### PR DESCRIPTION
**Pull request by Akanksha-Sen**

### CODE REVIEW

**Comment by avinash201199** [comment]
please add screenshot of the footer

**Comment by Akanksha-Sen** [comment]
image
image
image

**Comment by avinash201199** [comment]
please resolve conflicts

**Comment by avinash201199** [comment]
good work :)

**Comment by Akanksha-Sen** [comment]
resolved sir!

**Comment by avinash201199** [comment]
Thank you for your contribution

**Pull request merged**
